AWSTemplateFormatVersion: "2010-09-09"

Description:
  "This stack will create the needs to run the real time processing data environment"

Resources:
  KinesisDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: RTStream
      RetentionPeriodHours: 24
      ShardCount: 1
      StreamModeDetails: 
        StreamMode: PROVISIONED
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: RTPool
      AllowUnauthenticatedIdentities: true
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RTTable
      KeySchema:
        -
          AttributeName: Name
          KeyType: String
        -
          AttributeName: Latitude
          KeyType: String
        -
          AttributeName: Longitude
          KeyType: String
